version: "3"
services:
  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGTZ: "Etc/UTC"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres:
  redis:
